### ISSUE TITLE
cucumber integration question

### ISSUE THREAD

**Issue by charlierudolph** [webdriverio/wdio-cucumber-framework#96]
I'm one of the maintainers for cucumber-js and am curious about the architecture of this project. Why exactly does this repo have its own formatter instead of using the built in ones in cucumber?

Also, are there any API changes to cucumber that would could be made in support of this plugin?

**Comment by Miladinho** [comment]
@christian-bromann 

Can you offer some insight into this issue?

**Comment by christian-bromann** [comment]
> Why exactly does this repo have its own formatter instead of using the built in ones in cucumber?

What do you mean by that? We can't support Cucumber build in reporters because WebdriverIO comes with own reporters that are specialised for e2e tests (they include session ids and capability information).

> Also, are there any API changes to cucumber that would could be made in support of this plugin?

Maybe. I know that we were not able to update cucumber because of some breaking changes. I wasn't able yet to figure these out. I think #88 kicked of some initial work on it.

**Comment by christian-bromann** [comment]
@charlierudolph we just updated the wdio-cucumber-framework to support the latest cucumber-js version. Let me know if you have any more qesutions. Also, you can find me in our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
